# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='estado',
        ),
        migrations.AddField(
            model_name='post',
            name='texto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
