# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 01:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0002_auto_20170806_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateField(blank=True, default=django.utils.datetime_safe.datetime.now)),
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='texto',
            new_name='producto',
        ),
        migrations.AddField(
            model_name='post',
            name='precio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='producto',
            field=models.ManyToManyField(to='lista.Post'),
        ),
    ]
