# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 22:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0003_auto_20170825_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='producto',
        ),
    ]
